<?php

namespace app\controllers;

use app\components\BaseController;
use app\models\Callback;
use yii\web\Response;

class CallbackController extends BaseController
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return Response
     */
    public function actionCreate(): Response
    {
        $params = \Yii::$app->request->post();
        $callback = new Callback();
        $callback->name = $params['name'];
        $callback->email = $params['email'];
        $callback->phone = $params['phone'];
        $callback->text = $params['text'];
        $callback->created_at = time();

        return $this->asJson(($callback->save()) ? ['success' => true] : ['success' => false, 'message' => json_encode($callback->getErrorSummary())]);
    }
}